/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_goforbroke1006_algorithm_JarvisMarch */

#ifndef _Included_com_goforbroke1006_algorithm_JarvisMarch
#define _Included_com_goforbroke1006_algorithm_JarvisMarch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_goforbroke1006_algorithm_JarvisMarch
 * Method:    jarvisMarch
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_goforbroke1006_algorithm_JarvisMarch_jarvisMarch
  (JNIEnv *, jclass, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
